name       : kakoune
version    : 2020.09.01
release    : 7
source     :
    - https://github.com/mawww/kakoune/archive/v2020.09.01.tar.gz : bab18fdb8ea7b5ef25e953f56ec414e9bac42ee82baf9c462c69d5607858d026
homepage   : http://kakoune.org
license    : Unlicense
component  : editor
summary    : kakoune, mawww's experiment for a better code editor
description: |
    Kakoune is a code editor that implements Vi’s "keystrokes as a text editing language" model. As it’s also a modal editor, it is somewhat similar to the Vim editor (after which Kakoune was originally inspired).
builddeps  :
    - asciidoc
build      : |
    %make -C src
install    : |
    %make_install -C src PREFIX='/usr'
