name       : kakoune
version    : 2021.10.28
release    : 9
source     :
    - https://github.com/mawww/kakoune/archive/refs/tags/v2021.10.28.tar.gz : 4aa78c19108e15490d590f95f727dab67f33fc3c4358fbfc316b4a5f3f1d6b42
homepage   : https://kakoune.org
license    : Unlicense
component  : editor
summary    : kakoune, mawww's experiment for a better code editor
description: |
    Kakoune is a code editor that implements Vi’s "keystrokes as a text editing language" model. As it’s also a modal editor, it is somewhat similar to the Vim editor (after which Kakoune was originally inspired).
builddeps  :
    - asciidoc
build      : |
    %make -C src
install    : |
    %make_install -C src PREFIX='/usr'
