name       : kakoune
version    : 2021.11.08
release    : 10
source     :
    - https://github.com/mawww/kakoune/archive/refs/tags/v2021.11.08.tar.gz : 0885dc65377057fcfea0e7053d01d95a83668ec1907aced84dface8e00b83dee
homepage   : https://kakoune.org
license    : Unlicense
component  : editor
summary    : kakoune, mawww's experiment for a better code editor
description: |
    Kakoune is a code editor that implements Vi’s "keystrokes as a text editing language" model. As it’s also a modal editor, it is somewhat similar to the Vim editor (after which Kakoune was originally inspired).
builddeps  :
    - asciidoc
build      : |
    %make -C src
install    : |
    %make_install -C src PREFIX='/usr'
