name       : kakoune
version    : 2023.07.29
release    : 13
source     :
    - https://github.com/mawww/kakoune/archive/refs/tags/v2023.07.29.tar.gz : 0fbefc81783903b7301359cbc2e0754ba008af6f2f6ef83651a32eec7375497b
homepage   : https://kakoune.org
license    : Unlicense
component  : editor
summary    : kakoune, mawww's experiment for a better code editor
description: |
    Kakoune is a code editor that implements Vi’s "keystrokes as a text editing language" model. As it’s also a modal editor, it is somewhat similar to the Vim editor (after which Kakoune was originally inspired).
builddeps  :
    - asciidoc
build      : |
    %make -C src
install    : |
    %make_install -C src PREFIX='/usr'

    # Set EDITOR and VISUAL defaults should nano be removed.
    install -Dm00644 $pkgfiles/80-kakoune-is-default-EDITOR-and-VISUAL.sh $installdir/usr/share/defaults/etc/profile.d/80-kakoune-is-default-EDITOR-and-VISUAL.sh
    install -Dm00644 $pkgfiles/80-kakoune-is-default-EDITOR-and-VISUAL.fish $installdir/usr/share/defaults/etc/profile.d/80-kakoune-is-default-EDITOR-and-VISUAL.fish
